package id.go.lombokbaratkab.sumirah.tugasempat.model

data class Team(
        val idTeam: String? = null,
        val idSoccerXML: String? = null,
        val intLoved: String? = null,
        val strTeam: String? = null,
        val strTeamShort: String? = null,
        val strAlternate: String? = null,
        val intFormedYear: String? = null,
        val strSport: String? = null,
        val strLeague: String? = null,
        val idLeague: String? = null,
        val strDivision: String? = null,
        val strManager: String? = null,
        val strStadium: String? = null,
        val strKeywords: String? = null,
        val strRSS: String? = null,
        val strStadiumThumb: String? = null,
        val strStadiumDescription: String? = null,
        val strStadiumLocation: String? = null,
        val intStadiumCapacity: String? = null,
        val strWebsite: String? = null,
        val strFacebook: String? = null,
        val strTwitter: String? = null,
        val strInstagram: String? = null,
        val strDescriptionEN: String? = null,
        val strDescriptionDE: String? = null,
        val strDescriptionFR: String? = null,
        val strDescriptionCN: String? = null,
        val strDescriptionIT: String? = null,
        val strDescriptionJP: String? = null,
        val strDescriptionRU: String? = null,
        val strDescriptionES: String? = null,
        val strDescriptionPT: String? = null,
        val strDescriptionSE: String? = null,
        val strDescriptionNL: String? = null,
        val strDescriptionHU: String? = null,
        val strDescriptionNO: String? = null,
        val strDescriptionIL: String? = null,
        val strDescriptionPL: String? = null,
        val strGender: String? = null,
        val strCountry: String? = null,
        val strTeamBadge: String? = null,
        val strTeamJersey: String? = null,
        val strTeamLogo: String? = null,
        val strTeamFanart1: String? = null,
        val strTeamFanart2: String? = null,
        val strTeamFanart3: String? = null,
        val strTeamFanart4: String? = null,
        val strTeamBanner: String? = null,
        val strYoutube: String? = null,
        val strLocked: String? = null

)